<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01 - User</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5635e605-bdef-427e-8c71-b98d27a0c554</testSuiteGuid>
   <testCaseLink>
      <guid>a93d3c55-8f3d-4914-ab2e-4c14055080b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI Test Cases/UI01 - User/TC01 - Verify user gets an error message when signing up a user without email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b763495-ee60-4dfe-b713-b123af8f3d36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05b3e3b4-3b10-4bf5-9a39-edbc3f26877f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0aa5811-e6cd-4747-88aa-7ddcda1e067f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb589c45-ebe9-48ab-8ac4-ae1813f81e16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e3f814d-8958-4e82-936e-9862265d43ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73e73658-1470-44cc-b590-17348f4bb195</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI Test Cases/UI01 - User/TC02 - Verify user gets an error message when signing up with password less than 7 chars</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3416db6b-ad84-43fe-8828-77ad075aec34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ce92de8-a8ca-4ff5-9803-0caa7e37a335</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>645c9d30-2a7d-4ac4-a953-0169be6326d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8db19b55-4d8f-494d-8634-6dcae6358ed5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9a7d905-2ce3-4d12-a00a-142de16cb3cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7183f20-5cc5-42f0-b44c-a65c7967d267</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI Test Cases/UI01 - User/TC03 - Verify user can login successfully</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a958f1d-b2f7-4f06-937c-9e913a055fe6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ef95e96-bce6-488e-82e0-66e27d65d8c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42480cbb-d46e-4007-9701-32c713fd873f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2567dda7-fa33-42b0-9532-3eeaaf827096</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0508024-356d-47f0-b41e-f73d3c0627a8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
